{
 "title": "Presearch Node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pre_client", "label": "Client", "query": { "query": "pre_node_info" } }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Rewards (Total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(pre_total_pre_earned{pre_client=~\"$pre_client\"}[24h])/60) by (pre_client)\n* on(node_id) group_left(node_description, node_url, gateway_pool, remote_addr, version)\nsum(pre_node_info)",
     "legendFormat": "Daily ({{pre_client}})"
    },
    {
     "expr": "sum(sum_over_time(pre_total_pre_earned{pre_client=~\"$pre_client\"}[7d])/60) by (pre_client) /7\n* on(node_id) group_left(node_description, node_url, gateway_pool, remote_addr, version)\nsum(pre_node_info)",
     "legendFormat": "Weekly ({{pre_client}})"
    }
   ]
  },
  {
   "title": "Last 24 Rewards (by node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time(pre_total_pre_earned{pre_client=~\"$pre_client\"}[24h])\n* on(node_id) group_left(node_description, node_url, gateway_pool, remote_addr, version)\npre_node_info",
     "legendFormat": "{{node_description}}"
    }
   ]
  },
  {
   "title": "Last 24 Success Requests (by node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum_over_time(pre_successful_requests{pre_client=~\"$pre_client\"}[24h])\n* on(node_id) group_left(node_description, node_url, gateway_pool, remote_addr, version)\npre_node_info",
     "legendFormat": "{{node_description}}"
    }
   ]
  },
  {
   "title": "Node Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "pre_connected{pre_client=~\"$pre_client\"}\n* on(node_id) group_left(node_description, node_url, gateway_pool, remote_addr, version)\npre_node_info",
     "legendFormat": "{{node_description}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "pre_connected{pre_client=~\"$pre_client\"}\n* on(node_id) group_left(node_description, node_url, gateway_pool, remote_addr, version)\npre_node_info",
     "legendFormat": "{{pre_client}} {{node_description}}"
    }
   ]
  }
 ]
}